# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Build OpenID RP CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - id: checkout_repo
      uses: actions/checkout@v3

    - id: build_with_node
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install
    - run: npm run build:openid --if-present

    - id: upload_argetifacts
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: compiled-app
        path: ./dist/openid-rp/browser
    
